# **텐서와 데이터 로더**

## **1. 텐서 이해하기**

In [1]:
import torch
import numpy as np
import pandas as pd

### (1) 0-way Tensor

In [2]:
scalar = torch.tensor(5)
print(scalar)
print(scalar.shape)

tensor(5)
torch.Size([])


### (2) 1-way Tensor

In [3]:
vector = torch.tensor([1, 2, 3, 4])
print(vector)
print(vector.shape)

tensor([1, 2, 3, 4])
torch.Size([4])


### (3) 2-way Tensor

In [5]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(matrix.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


### (4) 3-way Tensor

In [6]:
tensor3d = torch.rand(2, 3, 4)
print(tensor3d)
print(tensor3d.shape)

tensor([[[0.2126, 0.6267, 0.5929, 0.5683],
         [0.4251, 0.5990, 0.5752, 0.1524],
         [0.6695, 0.7283, 0.6848, 0.3672]],

        [[0.1179, 0.7438, 0.5038, 0.4301],
         [0.4884, 0.5396, 0.5504, 0.4529],
         [0.5970, 0.1333, 0.4250, 0.0103]]])
torch.Size([2, 3, 4])


## **2. 텐서 다루기**

### (1) 텐서의 데이터 타입 지정

In [7]:
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print(int_tensor)
print(float_tensor)

tensor([1, 2, 3])
tensor([1., 2., 3.])


### (2) 텐서 속성 확인

In [8]:
print(float_tensor)
print(f'Shape: {float_tensor.shape}')
print(f'Datatype: {float_tensor.dtype}')
print(f'Device: {float_tensor.device}')

tensor([1., 2., 3.])
Shape: torch.Size([3])
Datatype: torch.float32
Device: cpu


### (3) 텐서 연산하기

In [9]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
print('덧셈:', a + b)
print('곱셈:', a * b)
print('제곱:', a ** 2)

덧셈: tensor([5., 7., 9.])
곱셈: tensor([ 4., 10., 18.])
제곱: tensor([1., 4., 9.])


### (4) 텐서 집계하기

In [10]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print('전체 합계:', x.sum())
print('열별 합계:', x.sum(dim=0))
print('행별 합계:', x.sum(dim=1))

전체 합계: tensor(21.)
열별 합계: tensor([5., 7., 9.])
행별 합계: tensor([ 6., 15.])


### (5) 텐서 차원 변경

In [11]:
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
print('원래 텐서:', x)
reshaped = x.view(2, 3)
print('변형된 텐서:', reshaped)

원래 텐서: tensor([[1, 2],
        [3, 4],
        [5, 6]])
변형된 텐서: tensor([[1, 2, 3],
        [4, 5, 6]])


### (6) 텐서 연결과 분리

In [12]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6]])

# 텐서 연결하기
concatenated = torch.cat([a, b], dim=0)
print('연결된 텐서:\n', concatenated)

연결된 텐서:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [13]:
# 텐서 분리하기
x = torch.tensor([1, 2, 3, 4, 5, 6])
split1, split2 = torch.split(x, 3)
print('분리된 텐서:', split1, split2)

분리된 텐서: tensor([1, 2, 3]) tensor([4, 5, 6])


### (7) 텐서 내적과 행렬곱

In [14]:
# 내적
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
dot = torch.dot(a, b)
print('Dot product:', dot)

Dot product: tensor(32)


In [16]:
# 행렬곱
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

result = torch.matmul(A, B)
print(result)

tensor([[19, 22],
        [43, 50]])


## **3. Data Loader**

### (1) 넘파이 배열→텐서 변환

In [17]:
path = 'https://bit.ly/advertising_csv'
adv = pd.read_csv(path)
target = 'Sales'
x = adv.drop(target, axis=1)
y = adv.loc[:, target]
x_np = x.values
y_np = y.values
print(type(x_np))
print(x_np.shape)

<class 'numpy.ndarray'>
(200, 3)


In [18]:
# 넘파이 배열 x, y를 텐서로 변환
x_tensor = torch.tensor(x_np, dtype=torch.float32)
y_tensor = torch.tensor(y_np, dtype=torch.float32)
print(x_tensor.shape, y_tensor.shape)

torch.Size([200, 3]) torch.Size([200])


### (2) x 텐서, y 텐서 → 텐서 데이터 세트 변환

In [19]:
from torch.utils.data import DataLoader, TensorDataset
dataset = TensorDataset(x_tensor, y_tensor)
print(dataset[:3])
print(len(dataset))

(tensor([[230.1000,  37.8000,  69.2000],
        [ 44.5000,  39.3000,  45.1000],
        [ 17.2000,  45.9000,  69.3000]]), tensor([22.1000, 10.4000,  9.3000]))
200


### (3) 텐서 데이터 세트로 데이터 로더 선언

In [20]:
# 데이터 로더 생성
data_loader = DataLoader(dataset, batch_size = 32, shuffle = True)

In [21]:
for n, batch in enumerate(data_loader):
    x_batch, y_batch = batch
    print(f'배치 {n}, x 배치 크기:{x_batch.shape}')

배치 0, x 배치 크기:torch.Size([32, 3])
배치 1, x 배치 크기:torch.Size([32, 3])
배치 2, x 배치 크기:torch.Size([32, 3])
배치 3, x 배치 크기:torch.Size([32, 3])
배치 4, x 배치 크기:torch.Size([32, 3])
배치 5, x 배치 크기:torch.Size([32, 3])
배치 6, x 배치 크기:torch.Size([8, 3])


## **4. 디바이스 할당: GPU 혹은 CPU에 할당하기**

### (1) 데이터 준비

In [22]:
# 라이브러리 로딩
import torch
from torch import nn
import numpy as np
import pandas as pd

# 데이터 로딩 및 x, y 분할
path = 'https://bit.ly/advertising_csv'
adv = pd.read_csv(path)

target = 'Sales'
x = adv.drop(target, axis=1)
y = adv.loc[:, target]

# numpy로 변환한 다음 텐서로 변환
x_np = x.values
y_np = y.values
x_tensor = torch.tensor(x_np, dtype=torch.float32)
y_tensor = torch.tensor(y_np, dtype=torch.float32)

### (2) 디바이스 준비


In [25]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Using {device} device.')

Using cuda device.


### (3) 모델과 데이터세트를 디바이스에 할당

In [26]:
# 모델을 디바이스(GPU)에 할당하기
model = nn.Sequential( nn.Linear(3, 1) )
model = model.to(device)

In [27]:
# 데이터 세트를 디바이스에 할당.
x, y = x_tensor.to(device), y_tensor.to(device)

In [28]:
# 디바이스 확인
print(next(model.parameters()).device)
print(x.device, y.device)

cuda:0
cuda:0 cuda:0
